### ISSUE TITLE
Make the complexity of extent types a little more clear

### ISSUE THREAD

**Issue by jlperla** [kokkos/array_ref#19]
I think that non-specialist readers comparing this to the array_view proposal are going to have a little trouble understanding why we need all these types for the extents.  An extra paragraph may help.  Something like the following, perhaps in Section 3:
-------
"Beyond the speedups due to optimal algorithms with better cache locality possible with flexible storage layout, the main feature to achieve zero-overhead abstraction is (potentially) static extents and strides.

For example, with C-style storage layout, a compiler can optimize access to a double[0][3] array by knowing that the first stride is a static 3.  To enable these sorts of optimizations, we need to allow for constexpr extents in the type, and use them where appropriate in operator().  So,
view< int[][3] > array( buffer , L );
static_assert(std::is_same<decltype(array.extent(1)), ?????>::value, "Static type"); //TODO, wasn't sure how to show the differences.
constexpr const std::size_t extent_1 = array.extent(1);

For strided layouts, this is also important.  For example, a slide of an entire column in the above array give a strided_layout, where the stride is statically known to be 3.

**Comment by hcedwar** [comment]
Added discussion to specifically address this performance consideration in P0331.
