### ISSUE TITLE
Range paper on proxy iterators

### ISSUE THREAD

**Issue by jlperla** [kokkos/array_ref#21]
See http://open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0022r0.html

Sounds like this problem is basically solved for the range.  If we knew about this earlier, it may have been possible to add in in iterators to the current design.  This stuff is above my head, but it sounds like:
 * The `ValueType` and `ReferenceType` would end up being `view` with potentially strided layout for ours (in general), potentially with the static extents depending on where the iterator is.
 * Then an `iter_swap` is necessary to be defined.  I think this would basically just copy the data between the slices of the view referenced, and I see no problem with it.
 * I don't know what `iter_move` means with these sorts of setups, but I suspect that isn't an issue particular to this setup (e.g., what does `iter_move` look like with `std::array<int,10>` right now?

**Comment by hcedwar** [comment]
Rather that doing generalized iteration which would require proxy iterators we went a simpler and guaranteed performant direction of requiring `is_contiguous` for simple iterators to be valid, and not supporting iteration of non- `is_contiguous` array reference.
