### ISSUE TITLE
Question about the implementation

### ISSUE THREAD

**Issue by mbianco** [kokkos/array_ref#22]
Thanks Carter for the updated version,

In the implementation there is a decoupling between layout types and offsets. This would make extendability a little complex since a user should define a tag-type plus an implementation as partial specialization of a (std::) library template.  And you still need to model some offset concept.
What I would prefer is to have the layout-offset to model the offset concept so that the extendability does not have to pass through a specialization. The user just have to implement a template class with a give interface. What's the rationale behind the current implementation?

I think this would make even easier to produce a generic affine layout in which the order of the strides are specified at compile time, so that layout_left and layout_right could be simple alias templates of this generic class (I should provide an implementation, shouldn't I?). We are using something similar in our library, a stripped example of implementation can be found in https://github.com/crosetto/examples_cpp/blob/master/Code/Solution/storage_info_sol.hpp#L30 in which the layout map specifies the permutation to apply to the indices in order to get the offsets.

Does any of this make sense to anybody?

**Comment by hcedwar** [comment]
This layout extension strategy has been incorporated into the proposal.
