### ISSUE TITLE
bikeshed processing

### ISSUE THREAD

**Issue by hcedwar** [kokkos/array_ref#39]
@dhollman : Need to add instructions for bikeshed processing / viewing / converting so that paper source files can be verified before commits & merges.  Github doesn't have an automatic viewing feature for ``.bs`` like its does for ``.md`` and ``.rst``

**Comment by hcedwar** [comment]
Documentation: https://tabatkins.github.io/bikeshed/
converter / viewer: https://api.csswg.org/bikeshed/

**Comment by hcedwar** [comment]
@dhollman : I just ran P0332.bs through the converter; numerous formatting errors to be addressed.

**Comment by dhollman** [comment]
> Github doesn't have an automatic viewing feature for .bs like its does for .md and .rst
Hmmm... that is a good point. Seems like a downside of using bikeshed. I know there's a way to get Travis CI to generate the html for your bikeshed documents.

**Comment by dhollman** [comment]
> I just ran P0332.bs through the converter; numerous formatting errors to be addressed.

Do you mean in the document itself, or errors spit out by the bikeshed processor? I get a bunch of warnings because I haven't given IDs to my headings (which I don't link to anyway), but otherwise I don't see anything.

**Comment by hcedwar** [comment]
Examples are missing large chunks of code.
